force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Recipient_Number__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Number__c</fullName>
    <label>Recipient Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Sender_Number__c.field-meta.xml
<CustomField>
    <fullName>Sender_Number__c</fullName>
    <label>Sender Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/Test_MessagingLWCController.cls
@isTest
public class Test_MessagingLWCController {

    @isTest
    static void testGetMessages() {
        
        Contact testContact = new Contact();
        testContact.LastName = 'TestContact';
        testContact.Phone = '+919958501744';
        insert testContact;

        List<Message__c> testMessages = new List<Message__c>();
        for (Integer i = 0; i < 5; i++) {
            Message__c testMessage = new Message__c();
            testMessage.Contact__c = testContact.Id;
            testMessage.Recipient_Number__c = '+919958501744';
            testMessage.Sender_Number__c = '+12565734669';
            testMessages.add(testMessage);
        }
        
        Test.startTest();
        
        insert testMessages;
		MessagingLWCController.MessagingWrapper result = MessagingLWCController.getMessages(testContact.Id, '0');
        
        Test.stopTest();

        System.assertEquals(testContact.Id, result.contactRecord.Id);
        System.assertEquals(5, result.messages.size()); // Assuming 5 messages were inserted
    }

    @isTest
    static void testCreateMessage() {
        
        Contact testContact = new Contact();
        testContact.LastName = 'TestContact';
        testContact.Phone = '+919958501744';
        insert testContact;

        Test.startTest();

        MessagingLWCController.createMessage('Test message', testContact.Id);

        Test.stopTest();

        List<Message__c> messages = [SELECT Id FROM Message__c WHERE Contact__c = :testContact.Id];
        System.assertEquals(1, messages.size()); // Expecting one message record
    }
}