force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/Recipient_Number__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Number__c</fullName>
    <label>Recipient Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Sender_Number__c.field-meta.xml
<CustomField>
    <fullName>Sender_Number__c</fullName>
    <label>Sender Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/NewMessage__e/NewMessage__e.object-meta.xml
<CustomObject>
    <label>NewMessage</label>
    <pluralLabel>NewMessage</pluralLabel>
</CustomObject>

force-app/main/default/objects/NewMessage__e/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <label>Recipient</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MessageTriggerHelper.cls
public class MessageTriggerHelper {
    public MessageTriggerHelper() {
        
    }
    
    public static void afterInsertOperations(List<Message__c> newMessages, Map<ID, SObject> newMessagesMap){
        List<NewMessage__e> newMessageEvents = new List<NewMessage__e>();

        for (Message__c message : newMessages) {
             NewMessage__e newMessageEvent = new NewMessage__e(
                Sender__c = message.Sender_Number__c,
                Recipient__c = message.Recipient_Number__c
            );
    
            newMessageEvents.add(newMessageEvent);
        }
        
        try {
            EventBus.publish(newMessageEvents);
        } catch (Exception e) {
            System.debug('Error publishing platform events: ' + e.getMessage());
        }
    }   
}