force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Is_Outbound__c.field-meta.xml
<CustomField>
    <fullName>Is_Outbound__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Outbound</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/MessagingLWCController.cls
public with sharing class MessagingLWCController {
    
    @AuraEnabled(cacheable = true)
    public static List<Message__c> getMessages(String contactId){
            List<Message__c> listOfMessages = [Select Id,Is_Outbound__c, Message_Content__c, CreatedBy.name, CreatedDate, Contact__r.Name from Message__c WHERE Contact__c=: contactId ORDER BY CreatedDate ];
            return listOfMessages;
    }
    
    @AuraEnabled
    public static void createMessage(String messageBody,String contactId){
        Contact conRec = [SELECT Phone from Contact where Id =:contactId LIMIT 1];
        TwilioSendSMS.SendSMS(messageBody,String.valueOf(conRec.Phone));
        Message__c messageRec = new Message__c();
        messageRec.Is_Outbound__c = true;
        messageRec.Message_Content__c = messageBody;
        messageRec.Contact__c = contactId;
        insert messageRec;
        
    }
}