force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/Is_Outbound__c.field-meta.xml
<CustomField>
    <fullName>Is_Outbound__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Outbound</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Recipient_Number__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Number__c</fullName>
    <label>Recipient Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Sender_Number__c.field-meta.xml
<CustomField>
    <fullName>Sender_Number__c</fullName>
    <label>Sender Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/TwilioReceiveSMS.cls
/* Class Name : TwilioReceiveSMS
   Author : Sweta
   Description : This is a class for receiving messages from Twilio.
*/
@RestResource(urlMapping='/TwilioReceiveSMS/*')
global class TwilioReceiveSMS {
    
    @HttpGet
    global static void getSMS() {
        RestRequest req = RestContext.request;       
        Map<String, String> sms = req.params; 

        String fromPhoneNumber;
        String smsBody;
        String toNumber;
        
		if (sms.containsKey('From')){
            fromPhoneNumber = sms.get('From') ;
        }
        if (sms.containsKey('Body')){
            smsBody = sms.get('Body') ;
        }   
        if (sms.containsKey('To')){
            toNumber = sms.get('To') ;
        }    
        
        if(String.isNotBlank(fromPhoneNumber)){
            Message__c messageRec = new Message__c(
                Is_Outbound__c = false,
                Message_Content__c = smsBody,
                Recipient_Number__c = toNumber,
                Sender_Number__c = fromPhoneNumber
            );
            
            try {
                insert as User messageRec;
            } catch (Exception e) {
                System.debug('Error while saving SMS message: ' + e.getMessage());
            }
        }
    }
}